name: Autoreply to Issues Opened for TSDB

on: [issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.ACCESS_TOKEN }}
        issue-message: "Hi there,<br><br>Thank you so much for your attention to TSDB! If you find TSDB helpful to your work, please star⭐️ this repository. Your star is your recognition, which can help more people notice TSDB this useful tool. It matters and is definitely a kind of contribution.<br><br>I have received your message and will respond ASAP. Thank you for your patience! 😃<br><br>Best,<br>Wenjie"
